# Generated by Django 4.2.1 on 2023-06-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoAluno', models.CharField(max_length=100)),
                ('CodigoProfessor', models.CharField(max_length=100)),
                ('CodigoTurma', models.CharField(max_length=100)),
            ],
        ),
    ]
