# Generated by Django 4.2.1 on 2023-06-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhedisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocurso', models.CharField(max_length=100)),
                ('codigocdisciplina', models.CharField(max_length=100)),
            ],
        ),
    ]
